import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const UsersLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className="relative">
      <Navbar />
      {children}
      <Footer />
    </section>
  );
};

export default UsersLayout;
